const express=require('express');
const router=express.Router();
const homeController=require('../controllers/homeController');
router.get('/',homeController.homepage);
router.use('/users',require('./users'));
router.use('/posts',require('./posts'));
router.use('/comments',require('./comments'));
router.use('/likes',require('./likes'));
router.use('/friendships',require('./friendships'));
module.exports=router;